### ISSUE TITLE
Design Feedback

### ISSUE THREAD

**Issue by itstheonlychris** [authors-team/white-noise#1]
**Button styles**
Hover state is currently blue. Underline is good, but lets keep text white.

**Feature section**
Can we add a max-width here to match the Nav bar 
![image](https://user-images.githubusercontent.com/35537005/77193226-ea3c6580-6aab-11ea-9351-dbb2d85a7985.png)

**Comment by stevejwojcik** [comment]
- Changed hover state to white
- Closed Feature feature section in container.
